name: 'Ontrack CLI Validation'
description: 'GitHub action to create a validation run based on the GitHub workflow information using the Ontrack CLI'
inputs:
  project:
    description: |
      Name of the Yontrack project. If not set, the action will try to get the information
      from the current environment variables.
    required: false
  branch:
    description: |
      Name of the Yontrack branch. If not set, the action will try to get the information
      from the current environment variables.
    required: false
  build:
    description: |
      Name of the build to validate. If not set, the action will try to get the information
      from the current environment variables.
    required: false
  validation:
    description: |
      Name of the validation stamp to use for the creation of the validation run in Ontrack.
    required: true
  # Validation status
  status:
    description: |
      Status of the validation run, like PASSED, FAILED, etc. If not provided, Yontrack
      will attempts to compute the status from any data provided.
      
      Most of the time, you can use:
      
      ```yaml
      with:
        status: ${{ steps.npm-build.outcome == 'success' && 'PASSED' || 'FAILED' }}
      ```
    required: false
  # Validation data
  type:
    description: |
      Type of the validation data, as supported by the Ontrack CLI
    required: false
  flags:
    description: |
      Additional flags to pass to the Ontrack CLI command, typically to pass additional data. For example:

      type: tests
      flags: --passed 10 --skipped 8 --failed 1
    required: false
  # Ontrack CLI setup
  executable:
    description: Name of the Ontrack CLI executable
    required: false
    default: ontrack-cli
  # Misc.
  logging:
    description: Activate some logging
    required: false
    default: "false"
runs:
  using: 'node16'
  main: 'dist/index.js'
