name: 'Ontrack CLI Validation'
description: 'GitHub action to create a validation run based on the GitHub workflow information using the Ontrack CLI'
inputs:
  # Required inputs
  step-name:
    description: Name of the step in the current workflow job to take as a reference for the validation
    required: true
  project:
    description: |
      Name of the Ontrack project. If not set, the action will try to get the information
      from the current GitHub repository.
    required: false
  branch:
    description: |
      Name of the Ontrack branch.If not set, the action will try to get the information
      from the current Git branch.
    required: false
  validation:
    description: |
      Name of the validation stamp to use for the creation of the validation run in Ontrack.
    required: true
  build:
    description: |
      Name of the build to validate.
    required: true
  token:
    description: |
      GitHub token to use to get information about the workflow. The `github.token` should be enough is most
      of workflows.
    required: true
  # Validation data
  type:
    description: |
      Type of the validation data, as supported by the Ontrack CLI
    required: false
  flags:
    description: |
      Additional flags to pass to the Ontrack CLI command, typically to pass additional data. For example:

      type: tests
      flags: --passed 10 --skipped 8 --failed 1
    required: false
  # Ontrack CLI setup
  executable:
    description: Name of the Ontrack CLI executable
    required: false
    default: ontrack-cli
  # Misc.
  logging:
    description: Activate some logging
    required: false
    default: "false"
runs:
  using: 'node16'
  main: 'dist/index.js'
